import '@fontsource-variable/inter';
import '@fontsource-variable/playfair-display';
import '@fontsource-variable/playfair-display/wght-italic.css';
import '../styles/tokens.css';
import '../styles/base.css';
import '../styles/nav.css';
import '../styles/hero.css';
import '../styles/sections.css';
import '../styles/footer.css';
import { initTheme } from './theme.js';
import { initSmoothScroll } from './smooth.js';
import { initNav } from './nav.js';
import { initReveal } from './reveal.js';
import { initCounters } from './counters.js';
import { initStatement } from './statement.js';
import { initServices } from './services.js';
import { initWork } from './work.js';
import { initTestimonials } from './testimonials.js';
import { initBigText } from './bigtext.js';
import { initReel } from './reel.js';
import { initHeroStripes } from './hero-stripes.js';
import { initCursor } from './cursor.js';
import { initMagnetic } from './magnetic.js';
import { initForm } from './form.js';

initTheme();
initSmoothScroll();
initNav();
initReveal();
initCounters();
initStatement();
initServices();
initWork();
initTestimonials();
initBigText();
initReel();
initHeroStripes();
initCursor();
initMagnetic();
initForm();
